runtime: nodejs16
instance_class: F2
env_variables:
  NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
  GOOGLE_CLOUD_STORAGE_KEYFILE: ${GOOGLE_CLOUD_STORAGE_KEYFILE}
  GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
  # Add more environment variables as needed
handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /.*
    secure: always
    script: auto
