import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import FooterComponent from "@/components/FooterComponent";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/TranslationsProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
   icons: {
    icon: '/favicon.ico', // /public path
  },
};

const i18nNamespaces = ['navbar'];

export default async function RootLayout({ children, params: { locale } }) {
  const { t , resources} = await initTranslations(locale, i18nNamespaces);
  
  return (
    <html>
      <body className={inter.className}>
      <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}>
    
      <Navbar/>
      <ScrollToTopButton />
      <div className="h-24 w-screen"></div>
        {children}
        <FooterComponent/>
        
        </TranslationsProvider>
        </body>
      
    </html>
  );
}
